apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: qn8lpomcl-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: qn8lpomcl-go 
  name: qn8lpomcl-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: qn8lpomcl-go 
